//#define  __linux__
//#define  CONFIG_BACKEND_FILE
//#define  CONFIG_IEEE80211W
//#define  CONFIG_PEERKEY
//#define  ATH_GCM_SUPPORT
#define  CONFIG_DRIVER_ATHR
#define  CONFIG_WIRELESS_EXTENSION
#define  PKCS12_FUNCS
#define  CONFIG_CRYPTO_INTERNAL
//#define  CONFIG_INTERNAL_LIBTOMMATH
#define  LTM_FAST
#define  CONFIG_SHA256
#define  CONFIG_INTERNAL_SHA384
#define  CONFIG_INTERNAL_SHA512
#define  CONFIG_CTRL_IFACE
#define  CONFIG_CTRL_IFACE_UNIX
#define  CONFIG_NO_LINUX_PACKET_SOCKET_WAR

